on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Build Docker image
        run: |
          sudo docker build -t ntuimage /path/to/your/docker/project

      - name: Deploy to AWS VM
        run: |
          echo "$SSH_PRIVATE_KEY" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa
          ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@3.86.182.157 '
            sudo docker stop ntuContainer || true &&
            sudo docker rm ntuContainer || true &&
            sudo docker run -d -p 3000:3000 --name ntuContainer ntuimage'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.pipeline }}
